### ISSUE TITLE
Type of input different from TPMs?

### ISSUE THREAD

**Issue by PietroD** [broadinstitute/Celligner_ms#1]
Hi,
I see that you use log2(TPM + 1) as input.
What about using a matrix transformed with `vst` function from `DESeq2`?
Thanks

**Comment by acwarren** [comment]
You could use other transformations of the data, it is just important that the format matches between the two datasets that you are trying to align. In our case we use log2(TPM + 1) data for both the cell line and tumor data we are aligning, but if you had two datasets that were both of another transformation that you want to align that should work also. Celligner utilizes mutual nearest neighbor batch correction (https://www.nature.com/articles/nbt.4091) which was first intended for single cell data, which is normalized differently.

**Comment by PietroD** [comment]
Ok I see, thanks a lot.
I have another question. 
What would the best option be if I wanted to include more than 2 datasets?
From the functions I see that all is written for a one by one comparison if I am not wrong.

**Comment by acwarren** [comment]
The Celligner method isn't currently designed to align more than two datasets. We are working on how best to do this and hope to include some initial guidelines in the near future.
