### ISSUE TITLE
Error: typo in run_lm_stats_limma argument within find_differentially_expressed_genes

### ISSUE THREAD

**Issue by PietroD** [broadinstitute/Celligner_ms#2]
There is an error in `run_lm_stats_limma` function within `find_differentially_expressed_genes`.
If the number of clusters equals 2, the slot `seu_obj@meta.data$cluster` is called but it should be `seu_obj@meta.data$seurat_clusters`.

**Comment by acwarren** [comment]
Thank you for catching this. A new version has been pushed, updating how seurat objects are created so that a parameter 'cluster' is also created. The new version pushed also includes small changes to the analysis and changes to the figures to match the version of paper that will be published.
